---
title: "R Notebook"
output: html_notebook
---

```{r}
df <- readRDS(here("data", "STU_QQQ_5.rds"))
df %>% head()
```

```{r}
library(janitor)
df %>% 
  filter(CNT == "IRL") %>% 
  # haven::as_factor() %>% # changes to its value
  remove_empty() %>% # rows and columns
  remove_constant() -> dfI
dfI
```


```{r}
options(scipen = 999)
dfI %>% 
  summarise(across(where(is.labelled), \(x) attributes(x)$label)) %>% 
  tidylog::pivot_longer(everything(), names_to = "Column", values_to = "Description") %>% 
  rowwise() %>% 
  mutate(Type = sapply(Column, \(x) class(df[[x]])[3])) %>% 
  mutate(First_5_Values = sapply(Column, \(x) paste(head(na.omit(df[[x]]), 5) , collapse = ", "))) %>%
  mutate(naPercent = sapply(Column, \(x) dfI %>% zap_labels() %>% .[[x]] %>% is.na() %>% mean %>% "*"(100) %>% round(2))) -> dfI.desc
dfI.desc %>% View()
dfI.desc
```

```{r}
dfIZ <- dfI %>% zap_labels() # zap doesn't seem to fully work
```


```{r}
dfI.desc %>% View()
```



Siglas: 

* WLE -> Warm likelihood estimates
* ICT -> information and communication technologies (tipo telemoveis e pcs)

Colunas a agupar a priori
* TODO


```{r}
cor(dfI %>% select(PV1SCIE,PV1READ,PV1MATH))
```


```{r}
if(FALSE){
  dfI |> SmartEDA::ExpReport(op_file="temp.html")
}
```

```{r}
dfIZ %>% tibble() %>% arrow::write_csv_arrow(here("data", "filtered.csv")) #for sure zapping with csv
dfI.desc %>% write_rds(here("data", "description.rds"))
```

