---
title: "Projeto"
author: "grupo 6sigma"
date: "2023-05-10"
output: html_notebook
---

### Bibliotecas
```{r}
library(psych)
library(corrplot)
library(haven)
library(dplyr)
library(magrittr)
```

# Leitura dos dados
```{r}
dados <- readRDS(here("data", "STU_QQQ_5.rds"))
dados
```

## Omissos de cada coluna
```{r}
colSums(is.na(dados))
```

```{r}
# A coluna dos Paises não tem nulos
sum(is.na(dados$CNT))
```

## Países Existentes na base de dados
```{r}
unique(dados$CNT)
```

### Visualização das características de cada um dos países
```{r}
dados %>%
  mutate(NumNulos = rowSums(is.na(.))) %>%
  group_by(CNT) %>%
  summarize(TotalNulos = sum(NumNulos),
            NumLinhas = n(),
            PercentNulos = (TotalNulos / (NumLinhas * ncol(dados))) * 100,
            MeanScience = mean(PV1SCIE, na.rm = TRUE),
            MeanRead = mean(PV1READ, na.rm = TRUE),
            MeanMath = mean(PV1MATH, na.rm = TRUE),
            .groups = "drop") %>% 
  arrange(desc(NumLinhas))
```

# Irlanda
```{r}
Irlanda <- dados %>% filter(CNT == "IRL")
Irlanda
```

## Características da Irlanda
```{r}
dim(Irlanda)
describe(Irlanda)
```
## Limpeza dos valores omissos
```{r}
IrlandaSemiLimpa <- Irlanda %>% select(where(~ !all(is.na(.))))
dim(IrlandaSemiLimpa)
```

```{r}
IrlandaLimpa <- na.omit(IrlandaSemiLimpa)
dim(IrlandaLimpa)
```

```{r}
Irlanda <- IrlandaLimpa %>% select_if(is.numeric)
rm(IrlandaLimpa)
rm(IrlandaSemiLimpa)
```

```{r}
Irlanda
describe(Irlanda)
```

## Correlações das colunas
```{r}
#Correlation plot with colors (too many attributes)
correlation <- cor(Irlanda)
corrplot(correlation)

#Correlation matrix
round(correlation, 3)
```

```{r}
#KMO measure 
KMO(correlation)

cortest.bartlett(correlation)
```


## PCA
```{r}
#Scalling of attributes data
data_scaled <- scale(Irlanda, center = TRUE, scale = TRUE)

#Assume the number of components = 34
pc34 <- principal(data_scaled, nfactors=34, rotate="none")
pc34$loadings

#Screeplot - Find the elbow
plot(pc34$values, type = "b", main = "Scree plot for FIFA19 dataset",
     xlab = "Number of PC", ylab = "Eigenvalue") 

#Eigenvalues - Variances of the principal components 
round(pc34$values,3)

#Using Kaiser criterion (9 component solution)
#5 component solution without rotation
pc9 <- principal(data_scaled, nfactors=9, rotate="none", scores=TRUE)

#communality of 5 component solution
round(pc9$communality,3)

#5 component solution with rotation (varimax)
pc9r <- principal(data_scaled, nfactors=9, rotate="varimax")
pc9r$loadings
```